use_frameworks!

target 'SwiftWeekSlider_Example' do
  pod 'SwiftWeekSlider', :path => '../'

  target 'SwiftWeekSlider_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
